In [1]:
import logging
logger = logging.getLogger()
logger.basicConfig = logging.basicConfig(level=logging.DEBUG)
import ltns.logictensornetworks_wrapper as ltnw
import tensorflow as tf
import numpy as np
import ltns.logictensornetworks as ltn
import itertools
import argparse

/home/h37167mj/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/h37167mj/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/h37167mj/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/h37167mj/anaconda3/env

In [2]:
    biases = [-1e-8]

    lr = 0.01
    dc = 0.9
    ly = 20
    embedding_size = 20

    bi = 1
    iter_epoch = 1

    ltn.LAYERS = ly
    ltn.BIAS_factor = bi
    ltn.set_universal_aggreg('mean')

In [3]:
    folder_name = "reasoning_results/"

    entities = ["Cat", "Feline", "Mammal", "Agent", "Thing", "Dog", "Human",
                "Reptile", "Organization", "Company", "Animal", "Bank", "Snake", "Squirrel", "Dolphin", "Shark", "Bird",
                "Fish",
                "Lizard", "Crocodile", "BlueFish", "LilBird", "Eagle", "BaldEagle"]

    relationships = (
    ("Cat", "Feline"), ("Feline", "Mammal"), ("Mammal", "Animal"), ("Animal", "Agent"), ("Agent", "Thing"),
    ("Dog", "Mammal"), ("Human", "Mammal"), ("Organization", "Agent"), ("Company", "Organization"),
    ("Bank", "Company"), ("Snake", "Reptile"), ("Reptile", "Animal"),
    ("Dolphin", "Mammal"), ("Shark", "Fish"), ("Lizard", "Reptile"),
    ("Crocodile", "Reptile"), ("BlueFish", "Fish"),
    ("LilBird", "Bird"), ("Eagle", "Bird"), ("BaldEagle", "Bird"), ("Bird", "Animal"), ("Fish", "Animal"),
    ("Shark", "Fish"), ("Squirrel", "Mammal"))

In [4]:
    all_relationships = list(itertools.product(entities, repeat=2))

    ltnw.predicate("SubClass",embedding_size*2)

<function ltns.logictensornetworks.predicate.<locals>.pred(*args)>

In [5]:
    for l in entities:
        ltnw.constant(l, min_value=[0.] * embedding_size, max_value=[1.] * embedding_size)

    for a,c in relationships:
        string = "SubClass(" + a + "," + c + ")"
        logging.info(string)
        ltnw.axiom(string)

    ltnw.variable("a",tf.concat(list(ltnw.CONSTANTS.values()),axis=0))
    ltnw.variable("b",tf.concat(list(ltnw.CONSTANTS.values()),axis=0))
    ltnw.variable("c",tf.concat(list(ltnw.CONSTANTS.values()),axis=0))


INFO:root:SubClass(Cat,Feline)
INFO:root:SubClass(Feline,Mammal)
INFO:root:SubClass(Mammal,Animal)
INFO:root:SubClass(Animal,Agent)
INFO:root:SubClass(Agent,Thing)
INFO:root:SubClass(Dog,Mammal)
INFO:root:SubClass(Human,Mammal)
INFO:root:SubClass(Organization,Agent)
INFO:root:SubClass(Company,Organization)
INFO:root:SubClass(Bank,Company)
INFO:root:SubClass(Snake,Reptile)
INFO:root:SubClass(Reptile,Animal)
INFO:root:SubClass(Dolphin,Mammal)
INFO:root:SubClass(Shark,Fish)
INFO:root:SubClass(Lizard,Reptile)
INFO:root:SubClass(Crocodile,Reptile)
INFO:root:SubClass(BlueFish,Fish)
INFO:root:SubClass(LilBird,Bird)
INFO:root:SubClass(Eagle,Bird)
INFO:root:SubClass(BaldEagle,Bird)
INFO:root:SubClass(Bird,Animal)
INFO:root:SubClass(Fish,Animal)
INFO:root:SubClass(Shark,Fish)
INFO:root:SubClass(Squirrel,Mammal)


<tf.Tensor 'c:0' shape=(24, 20) dtype=float32>

In [6]:
    ltnw.axiom("forall a,b,c: (SubClass(a,b) & SubClass(b,c)) -> SubClass(a,c)")
    ltnw.axiom("forall a: ~SubClass(a,a)")
    ltnw.axiom("forall a,b: SubClass(a,b) -> ~SubClass(b,a)")


Instructions for updating:
Use `tf.cast` instead.


<tf.Tensor 'cond_2/Merge:0' shape=(1,) dtype=float32>

### Newly added classes

In [7]:
ltnw.axiom("~SubClass(Cat,Reptile)")
ltnw.axiom("~SubClass(Cat,Bird)")
ltnw.axiom("~SubClass(Cat,Fish)")

<tf.Tensor 'NOT_Reshape_64:0' shape=(1,) dtype=float32>

In [9]:
ltnw.CONSTANTS

{'Cat': <tf.Variable 'Variable:0' shape=(1, 20) dtype=float32_ref>,
 'Feline': <tf.Variable 'Variable_1:0' shape=(1, 20) dtype=float32_ref>,
 'Mammal': <tf.Variable 'Variable_2:0' shape=(1, 20) dtype=float32_ref>,
 'Agent': <tf.Variable 'Variable_3:0' shape=(1, 20) dtype=float32_ref>,
 'Thing': <tf.Variable 'Variable_4:0' shape=(1, 20) dtype=float32_ref>,
 'Dog': <tf.Variable 'Variable_5:0' shape=(1, 20) dtype=float32_ref>,
 'Human': <tf.Variable 'Variable_6:0' shape=(1, 20) dtype=float32_ref>,
 'Reptile': <tf.Variable 'Variable_7:0' shape=(1, 20) dtype=float32_ref>,
 'Organization': <tf.Variable 'Variable_8:0' shape=(1, 20) dtype=float32_ref>,
 'Company': <tf.Variable 'Variable_9:0' shape=(1, 20) dtype=float32_ref>,
 'Animal': <tf.Variable 'Variable_10:0' shape=(1, 20) dtype=float32_ref>,
 'Bank': <tf.Variable 'Variable_11:0' shape=(1, 20) dtype=float32_ref>,
 'Snake': <tf.Variable 'Variable_12:0' shape=(1, 20) dtype=float32_ref>,
 'Squirrel': <tf.Variable 'Variable_13:0' shape=(1, 20

In [14]:
ltnw.AXIOMS

{'SubClass(Cat,Feline)': <tf.Tensor 'Reshape_1:0' shape=(1,) dtype=float32>,
 'SubClass(Feline,Mammal)': <tf.Tensor 'Reshape_3:0' shape=(1,) dtype=float32>,
 'SubClass(Mammal,Animal)': <tf.Tensor 'Reshape_5:0' shape=(1,) dtype=float32>,
 'SubClass(Animal,Agent)': <tf.Tensor 'Reshape_7:0' shape=(1,) dtype=float32>,
 'SubClass(Agent,Thing)': <tf.Tensor 'Reshape_9:0' shape=(1,) dtype=float32>,
 'SubClass(Dog,Mammal)': <tf.Tensor 'Reshape_11:0' shape=(1,) dtype=float32>,
 'SubClass(Human,Mammal)': <tf.Tensor 'Reshape_13:0' shape=(1,) dtype=float32>,
 'SubClass(Organization,Agent)': <tf.Tensor 'Reshape_15:0' shape=(1,) dtype=float32>,
 'SubClass(Company,Organization)': <tf.Tensor 'Reshape_17:0' shape=(1,) dtype=float32>,
 'SubClass(Bank,Company)': <tf.Tensor 'Reshape_19:0' shape=(1,) dtype=float32>,
 'SubClass(Snake,Reptile)': <tf.Tensor 'Reshape_21:0' shape=(1,) dtype=float32>,
 'SubClass(Reptile,Animal)': <tf.Tensor 'Reshape_23:0' shape=(1,) dtype=float32>,
 'SubClass(Dolphin,Mammal)': <t

In [9]:
    ltnw.initialize_knowledgebase(
        optimizer=tf.train.RMSPropOptimizer(learning_rate=lr,decay=dc),
        formula_aggregator=lambda *x: tf.reduce_min(tf.concat(x, axis=0)))

    # Train the KB
    sat_level = ltnw.train(max_epochs=10000)

    print(sat_level)

INFO:ltns.logictensornetworks_wrapper:Initializing knowledgebase
INFO:ltns.logictensornetworks_wrapper:Initializing Tensorflow session

INFO:ltns.logictensornetworks_wrapper:Initializing optimizer
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:ltns.logictensornetworks_wrapper:Assembling feed dict
INFO:ltns.logictensornetworks_wrapper:INITIALIZED with sat level = 0.00062467507
INFO:ltns.logictensornetworks_wrapper:TRAINING 0 sat level -----> 0.00062467507
INFO:ltns.logictensornetworks_wrapper:TRAINING 100 sat level -----> 0.30973482
INFO:ltns.logictensornetworks_wrapper:TRAINING 200 sat level -----> 0.74927145
INFO:ltns.logictensornetworks_wrapper:TRAINING 300 sat level -----> 0.80791664
INFO:ltns.logictensornetworks_wrapper:TRAINING 400 sat level -----> 0.9052389
INFO:ltns.logictensornetworks_wrapper:TRAINING 500 sat l

0.9925368


In [15]:
for a,b in all_relationships:
            print(a + "," + b + "," + np.array_str(ltnw.ask("SubClass("+ a +"," + b +")").squeeze()) + "\n")

Cat,Cat,0.00059466413

Cat,Feline,0.9999968

Cat,Mammal,0.9999945

Cat,Agent,0.99994636

Cat,Thing,0.75432396

Cat,Dog,0.00016645204

Cat,Human,0.0055557936

Cat,Reptile,0.99999964

Cat,Organization,0.87741715

Cat,Company,0.029962646

Cat,Animal,0.23949185

Cat,Bank,0.008761546

Cat,Snake,0.015906421

Cat,Squirrel,9.798092e-07

Cat,Dolphin,0.24352561

Cat,Shark,1.5420082e-05

Cat,Bird,0.99159265

Cat,Fish,0.9975587

Cat,Lizard,0.0010509674

Cat,Crocodile,0.018907247

Cat,BlueFish,0.0019477162

Cat,LilBird,0.0030957079

Cat,Eagle,0.000642166

Cat,BaldEagle,0.0030233043

Feline,Cat,1.2013999e-06

Feline,Feline,0.000102640384

Feline,Mammal,0.9999877

Feline,Agent,0.010524224

Feline,Thing,0.17177026

Feline,Dog,9.497111e-08

Feline,Human,5.1865854e-06

Feline,Reptile,0.5233667

Feline,Organization,0.19528383

Feline,Company,0.00593978

Feline,Animal,0.60020447

Feline,Bank,0.00015612431

Feline,Snake,8.7670617e-07

Feline,Squirrel,9.632848e-07

Feline,Dolphin,5.5129385e-07

Feline,Shark

In [10]:
cat_entity = entities[0]
for i in entities:
    print(cat_entity + "," + i + "," + np.array_str(ltnw.ask("SubClass("+ cat_entity +"," + i +")").squeeze()) + "\n")

Cat,Cat,3.9569775e-05

Cat,Feline,0.99940157

Cat,Mammal,0.97512484

Cat,Agent,0.94047254

Cat,Thing,5.2179865e-05

Cat,Dog,0.0005469491

Cat,Human,4.476549e-07

Cat,Reptile,0.00035871047

Cat,Organization,0.00886967

Cat,Company,0.023246493

Cat,Animal,0.006020819

Cat,Bank,0.0002652796

Cat,Snake,6.618946e-08

Cat,Squirrel,1.4261411e-05

Cat,Dolphin,0.00815643

Cat,Shark,2.375328e-06

Cat,Bird,0.0023594408

Cat,Fish,3.2753076e-05

Cat,Lizard,1.2627611e-06

Cat,Crocodile,7.157405e-05

Cat,BlueFish,2.7240375e-07

Cat,LilBird,2.5455407e-08

Cat,Eagle,4.582332e-07

Cat,BaldEagle,0.0039735963



In [16]:
ltnw.ask("forall a,b,c: (SubClass(a,b) & SubClass(b,c)) -> SubClass(a,c)")

array([0.9915311], dtype=float32)

In [17]:
ltnw.ask("forall a,b: SubClass(a,b) -> ~SubClass(b,a)")

array([0.9922321], dtype=float32)

In [16]:
ltnw.axiom("forall a,b: SubClass(a,b) -> ~SubClass(b,a)")

<tf.Tensor 'cond_2/Merge:0' shape=(1,) dtype=float32>

In [15]:
ltnw.AXIOMS.values()

dict_values([<tf.Tensor 'Reshape_1:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_3:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_5:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_7:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_9:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_11:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_13:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_15:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_17:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_19:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_21:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_23:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_25:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_27:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_29:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_31:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_33:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_35:0' shape=(1,) dtype=float32>, <tf.Tensor 'Reshape_37:0' shape=(1,) d

In [25]:
ltnw.CONSTANTS['Cat'].eval()

array([[ 0.43058312,  0.60139173,  0.21706615, -0.322368  , -0.0968331 ,
         0.9136105 ,  0.40308005, -0.1766784 ,  0.66436285,  0.5038559 ,
         0.29461694,  0.35135743,  0.23053262, -0.08328117,  0.96339756,
         0.69240075,  0.75066334,  0.4698674 ,  0.1819757 ,  0.08692741]],
      dtype=float32)

In [22]:
ltnw.VARIABLES['a'].eval()

array([[ 0.43058312,  0.60139173,  0.21706615, -0.322368  , -0.0968331 ,
         0.9136105 ,  0.40308005, -0.1766784 ,  0.66436285,  0.5038559 ,
         0.29461694,  0.35135743,  0.23053262, -0.08328117,  0.96339756,
         0.69240075,  0.75066334,  0.4698674 ,  0.1819757 ,  0.08692741],
       [ 0.07403434,  0.6554029 ,  0.69228137,  0.60480285,  0.18030663,
         0.05580373,  0.6630826 , -0.21119826,  0.63199186,  0.5202988 ,
         0.49993634,  0.8927348 , -0.27348852,  0.63334733,  0.29312646,
         0.6419266 ,  0.78252625,  0.85310364,  0.3830288 ,  0.72141725],
       [ 0.8116013 ,  0.52075213,  0.12422749,  0.785954  ,  0.72830796,
         0.51925784, -0.03148444,  0.25925183,  1.3610548 ,  1.0529555 ,
         0.64811873,  0.497145  ,  0.6165527 ,  0.5994126 , -0.02247924,
         0.23429374, -0.1924985 ,  1.0381521 ,  0.7900315 , -0.11515416],
       [ 0.00805716, -0.05159487,  0.7307308 , -0.26300594,  0.85729367,
         0.47397858,  0.49215505,  0.5196338 ,  

## EVALUTAION TEST

In [21]:
from utils import evaluation_utilities
import pprint
import os
from os import listdir
from os.path import isfile, join
from sklearn.metrics import matthews_corrcoef, f1_score, precision_score, recall_score, accuracy_score
import pandas as pd

gold_standard = os.getcwd() + "/../gold_standard/closed_tx"
prediction_file = os.getcwd()+ "/reasoning_results/tx_lr:0.01dc:0.9_em:10_ly:10_bi:-1e-05_iter:1_univ:hmean_sat:0.9855226"

closed = pd.read_csv(gold_standard, names=["first", "second", "type"])
testing = pd.read_csv(prediction_file, skiprows=[0], names=["first", "second", "type"])
data = pd.merge(closed, testing, on=["first", "second"])

In [24]:
data

first     second  type_x        type_y
0          Cat        Cat       0  2.840845e-07
1          Cat     Feline       1  9.993941e-01
2          Cat     Mammal       1  2.068011e-03
3          Cat      Agent       1  9.663942e-04
4          Cat      Thing       1  4.570394e-05
..         ...        ...     ...           ...
571  BaldEagle  Crocodile       0  1.336374e-05
572  BaldEagle   BlueFish       0  4.429243e-05
573  BaldEagle    LilBird       0  4.424861e-05
574  BaldEagle      Eagle       0  9.267724e-05
575  BaldEagle  BaldEagle       0  2.864367e-03

[576 rows x 4 columns]

In [87]:
zipped_data = []
zipped_data = zip(data["type_x"].values.tolist(), data["type_y"].values.tolist())

In [89]:
    mae = 0
    count = 0
    for a, b in zipped_data_list:
        mae = mae + abs(a - b)
        count += 1

In [90]:
mae

75.5708468781087

In [88]:
zipped_data_list = list(zipped_data)

In [91]:
y_actual = map(lambda x: x[0], zipped_data_list)
y_hat = map(lambda x: int(lucky_round(x)), map(lambda x: x[1], zipped_data_list))

In [64]:
np.fromiter(y_actual, dtype=np.float)

array([], dtype=float64)

In [95]:
list(y_hat)

[1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [94]:
def lucky_round(val, hold=0.5):
    if val >= hold:
        return 1
    else:
        return 0